config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  root "application#welcome"

  resources :lesson_events
  resources :assessment_scores
  devise_for :seekers, controllers: { registrations: "registrations/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :courses do
    resources :lessons
  end

  devise_scope :seeker do
  get "/welcome/index", to: "registrations#welcome"
  end

  #information
  get "/assessment_scores/science-of-spirituality", to: "assessment_scores#info"

  #data to csv export routes
  get("/export_courses", { :controller => "courses", :action => "export" })
  get("/export_lessons", { :controller => "lessons", :action => "export" })
  get("/export_aq", { :controller => "assessment_questions", :action => "export" })
  get("/export_as", { :controller => "assessment_scores", :action => "export" })

end

app/models/assessment_question.rb
# == Schema Information
#
# Table name: assessment_questions
#
#  id             :bigint           not null, primary key
#  name           :string
#  question       :string
#  spiritual_type :string
#  number         :integer
#  assessment     :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  course_id      :integer
#  lesson_id      :integer
#
class AssessmentQuestion < ApplicationRecord

  def self.to_csv
    require 'csv'
    aq = self.all
    headers = ["name", "question", "spiritual_type", "number", "assessment", "created_at","updated_at"]

    
    csv = CSV.generate(headers: true) do |csv|

      csv << headers

        aq.each do |aq_attr|
          row = []
          row.push(aq_attr.name)
          row.push(aq_attr.question)
          row.push(aq_attr.spiritual_type)
          row.push(aq_attr.number)
          row.push(aq_attr.assessment)
          row.push(aq_attr.created_at)
          row.push(aq_attr.updated_at)
          csv << row
        end
      end

      return csv

    end

end

app/controllers/assessment_questions_controller.rb
class AssessmentQuestionsController < ApplicationController
  before_action :set_assessment_question, only: %i[ show edit update destroy ]
  before_action :set_score

  # GET /assessment_questions or /assessment_questions.json
  def index
    @assessment_questions = AssessmentQuestion.all
  end

  # GET /assessment_questions/1 or /assessment_questions/1.json
  def show
  end

  # GET /assessment_questions/new
  def new
    @assessment_question = AssessmentQuestion.new
  end

  # GET /assessment_questions/1/edit
  def edit
  end

  # POST /assessment_questions or /assessment_questions.json
  def create
    @assessment_question = AssessmentQuestion.new(assessment_question_params)

    respond_to do |format|
      if @assessment_question.save
        format.html { redirect_to assessment_question_url(@assessment_question), notice: "Assessment question was successfully created." }
        format.json { render :show, status: :created, location: @assessment_question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assessment_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessment_questions/1 or /assessment_questions/1.json
  def update
    respond_to do |format|
      if @assessment_question.update(assessment_question_params)
        format.html { redirect_to assessment_question_url(@assessment_question), notice: "Assessment question was successfully updated." }
        format.json { render :show, status: :ok, location: @assessment_question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assessment_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessment_questions/1 or /assessment_questions/1.json
  def destroy
    @assessment_question.destroy

    respond_to do |format|
      format.html { redirect_to assessment_questions_url, notice: "Assessment question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def export
    aq = AssessmentQuestion.all
      
      respond_to do |format|
        format.html do
          render
        end
        format.csv do
           send_data(aq.to_csv, { :filename =>  "export_aq.csv"} )
        end
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment_question
      @assessment_question = AssessmentQuestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assessment_question_params
      params.fetch(:assessment_question, {})
    end
end

app/helpers/assessment_questions_helper.rb
module AssessmentQuestionsHelper
end

app/views/assessment_questions/_form.html.erb
<%= form_with(model: assessment_question) do |form| %>
  <% if assessment_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assessment_question.errors.count, "error") %> prohibited this assessment_question from being saved:</h2>

      <ul>
        <% assessment_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :spiritual_type %>
    <%= form.text_field :spiritual_type %>
  </div>

  <div class="field">
    <%= form.label :number_string %>
    <%= form.text_field :number_string %>
  </div>

  <div class="field">
    <%= form.label :assessment %>
    <%= form.text_field :assessment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assessment_questions/edit.html.erb
<h1>Editing Assessment Question</h1>

<%= render 'form', assessment_question: @assessment_question %>

<%= link_to 'Show', @assessment_question %> |
<%= link_to 'Back', assessment_questions_path %>

app/views/assessment_questions/export.html.erb
<div class="container-fluid">
<div class="card card-body col-md-6 container-fluid">
<%= link_to 'download', "/export_aq.csv" %>
</div>
</div>

app/views/assessment_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Assessment Questions</h3>

<br>

<% AssessmentQuestion.where(spiritual_type: spiritual_type.downcase, assessment: "spiritual_type").each do |assessment_question| %>
  <div class="row list-group-item">
    <div class="col-md-5">
      <div class="card card-body-question text-center" style="background-color: white;">
        <label for="q1-ideal"><%= assessment_question.question %></label>
      </div>
    </div>
    <div class="container col-md-7 align-self-center" style="margin-top: 1rem; margin-bottom: 1rem;">
      <div class="row">
        <div class="col text-left">
          Very Unimportant
        </div>
        <div class="col justify-content-end text-right">
          Very Important
        </div>
      </div>
      <div class="row">
        <div class="col">
          <input type="range" min="1" max="5" value="1" class="slider form-control-range" id="q1-ideal" step="1" name="q1-ideal" list="tickmarks">
          <datalist id="tickmarks">
            <option value="1" label="1"></option>
            <option value="2" label="2"></option>
            <option value="3" label="3"></option>
            <option value="4" label="4"></option>
            <option value="5" label="5"></option>
          </datalist>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/assessment_questions/new.html.erb
<h1>New Assessment Question</h1>

<%= render 'form', assessment_question: @assessment_question %>

<%= link_to 'Back', assessment_questions_path %>

app/views/assessment_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assessment_question.name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @assessment_question.question %>
</p>

<p>
  <strong>String:</strong>
  <%= @assessment_question.string %>
</p>

<p>
  <strong>Spiritual type:</strong>
  <%= @assessment_question.spiritual_type %>
</p>

<p>
  <strong>Number string:</strong>
  <%= @assessment_question.number_string %>
</p>

<p>
  <strong>Assessment:</strong>
  <%= @assessment_question.assessment %>
</p>

<%= link_to 'Edit', edit_assessment_question_path(@assessment_question) %> |
<%= link_to 'Back', assessment_questions_path %>