config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  root "application#welcome"

  resources :lesson_events
  resources :assessment_scores
  devise_for :seekers, controllers: { registrations: "registrations/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :courses do
    resources :lessons
  end

  devise_scope :seeker do
  get "/welcome/index", to: "registrations#welcome"
  end

  #information
  get "/assessment_scores/science-of-spirituality", to: "assessment_scores#info"

  #data to csv export routes
  get("/export_courses", { :controller => "courses", :action => "export" })
  get("/export_lessons", { :controller => "lessons", :action => "export" })
  get("/export_aq", { :controller => "assessment_questions", :action => "export" })
  get("/export_as", { :controller => "assessment_scores", :action => "export" })

end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id                   :bigint           not null, primary key
#  course_id            :integer
#  day                  :integer
#  title                :string
#  description          :string
#  learning_session_id  :integer
#  practice_session_id  :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  spiritual_type       :string
#  practice_description :string
#
class Lesson < ApplicationRecord
  has_many :lesson_events, class_name: "LessonEvent", foreign_key: "lesson_id"
  has_many  :assessment_questions, class_name: "AssessmentQuestion", foreign_key: "lesson_id"
  belongs_to :course, class_name: "Course", foreign_key: "course_id"

  #Route for Data Dump
  def self.to_csv
    require "csv"
    lessons = self.all
    headers = ["course_id", "practice_id", "day", "title", "description", "learning_session_id", "practice_session_id", "spiritual_type"]

    csv = CSV.generate(headers: true) do |csv|
      csv << headers

      lessons.each do |lesson_attr|
        row = []
        row.push(lesson_attr.course_id)
        row.push(lesson_attr.practice_id)
        row.push(lesson_attr.day)
        row.push(lesson_attr.title)
        row.push(lesson_attr.description)
        row.push(lesson_attr.learning_session_id)
        row.push(lesson_attr.practice_session_id)
        row.push(lesson_attr.spiritual_type)
        csv << row
      end
    end

    return csv
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :require_login
  before_action :set_course, only: %i[ show export ]
  before_action :set_lesson, only: %i[ show export ]
  before_action :set_lesson_event, only: %i[ show ]
  before_action :set_score, only: %i[ show ]
  


  # GET /lessons/1 or /lessons/1.json
  def show
      # Define Content Links
      @teaching_link = "teaching_content/course_" + @course.id.to_s + "/lesson_" + (@lesson.day.to_i).to_s
      @practice_link = "practice_content/course_" + @course.id.to_s + "/lesson_" + (@lesson.day.to_i).to_s
      @aq_count = @lesson.assessment_questions.count
  end

  def export
    lessons = Lesson.all
      
      respond_to do |format|
        format.html do
          render
        end
        format.csv do
           send_data(lessons.to_csv, { :filename =>  "export_lessons.csv"} )
        end
      end
  end

  private

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.fetch(:lesson, {})
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.number_field :day %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :learning_session_id %>
    <%= form.number_field :learning_session_id %>
  </div>

  <div class="field">
    <%= form.label :practice_session_id %>
    <%= form.number_field :practice_session_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/export.html.erb
<div class="container-fluid">
<div class="card card-body col-md-6 container-fluid">
<%= link_to 'download', "/export_lessons.csv" %>
</div>
</div>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Day</th>
      <th>Title</th>
      <th>Description</th>
      <th>Learning session</th>
      <th>Practice session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.course_id %></td>
        <td><%= lesson.day %></td>
        <td><%= lesson.title %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.learning_session_id %></td>
        <td><%= lesson.practice_session_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<div class="container">
  <div class="card" style="margin-top: 10vh">
    <div class="row">
      <h1 class="text-center">
        <%= "Day " + @lesson.day.to_s + ": " + @lesson.title.to_s %>
      </h1>
    </div>
  </div>
  <br class="invisible">
  <div class="container">
    <div class="card" id="accordionExample">
      <div class="accordion-item container-fluid">
        <div class="accordion-header" id="headingOne">
          <div class="row">
            <div class="col-10">
              <div class="row" style="margin-top: 5vh; margin-bottom 5vh">
                <h3>Today's Teaching:</h3>
              </div>
              <div class="row card-body">
                <%= @lesson.description%>
              </div>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <button id="collapseOneButton" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              </button>
            </div>
          </div>
        </div>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <br>
            <%= render partial: @teaching_link %>
            <div>
              <%= render partial: "lesson_events/form", locals: {study_session: @study_session, status_value: :teaching_done} %>
            </div>
          </div>

        </div>
      </div>
    </div>
    <br class="invisible">
    <div class="card" id="accordionExample">
      <div class="accordion-item container-fluid">
        <div class="accordion-header" id="headingTwo">
          <div class="row">
            <div class="col-10">
              <div class="row" style="margin-top: 5vh; margin-bottom 5vh">
                <h3>Today's Practice:</h3>
              </div>
              <div class="row card-body">
                <%= @lesson.practice_description%>
              </div>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <button id="collapseTwoButton" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              </button>
            </div>
          </div>
        </div>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <br>
            <%= render partial: @practice_link %>
            <div>
              <%= render partial: "lesson_events/form", locals: {study_session: @study_session, status_value: :practice_done} %>
            </div>
          </div>

        </div>
      </div>
    </div>

    <br class="invisible">
    <% if @lesson.has_assessment == true %>
      <div class="card" id="accordionExample">
        <div class="accordion-item container-fluid">
          <div class="accordion-header" id="headingThree">
            <div class="row">
              <div class="col-10">
                <div class="row" style="margin-top: 5vh; margin-bottom 5vh">
                  <h3>Today's Spiritual Assessment:</h3>
                </div>
              </div>
              <div class="col-2 d-flex justify-content-center">
                <button id="collapseThreeButton" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                </button>
              </div>
            </div>
          </div>
          <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <br>
              <%= render partial: "assessment_scores/form", locals: {study_session: @study_session, type_assessment: @lesson.spiritual_type, assessment_score: @type_score, aq_count: @aq_count} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <% if @lesson.is_final == true  %>
      <div>
        <%= render partial: "lesson_events/form_complete", locals: {study_session: @study_session, status_value: "complete" } %>
        <p>Thanks for trying our prototype!</p>
      </div>
    <% else %>
      <div>
        <%= render partial: "lesson_events/form_complete", locals: {study_session: @study_session, status_value: "complete" } %>
      </div>
    <% end %>
  </div>
  <br>
  <br>
</div>
</div>

app/views/lessons/show.js.erb
console.log("Updating Status");

<% if @study_session.status == "teaching_done" %>
$("#collapseOne").removeClass("show");
$("#collapseTwo").addClass("show");
$("#collapseOneButton").attr("aria-expanded","false");
$("#collapseTwoButton").attr("aria-expanded","true");
$("#collapseOneButton").addClass("collapsed");
$("#collapseTwoButton").removeClass("collapsed");

console.log("Teaching Done");

<% elsif @study_session.status == "practice_done" && @study_session.lesson.day < 5 %>

$("#collapseTwo").removeClass("show");
$("#collapseThree").addClass("show");
$("#collapseTwoButton").attr("aria-expanded","false");
$("#collapseThreeButton").attr("aria-expanded","true");
$("#collapseTwoButton").addClass("collapsed");
$("#collapseThreeButton").removeClass("collapsed");

console.log("Practice Done");

<% else %>

$("#collapseTwo").removeClass("show");
$("#collapseTwoButton").attr("aria-expanded","false");
$("#collapseTwoButton").addClass("collapsed");

console.log("Nothing Done");

<%end%>