config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  root "application#welcome"

  resources :lesson_events
  resources :assessment_scores
  devise_for :seekers, controllers: { registrations: "registrations/registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :courses do
    resources :lessons
  end

  devise_scope :seeker do
  get "/welcome/index", to: "registrations#welcome"
  end

  #information
  get "/assessment_scores/science-of-spirituality", to: "assessment_scores#info"

  #data to csv export routes
  get("/export_courses", { :controller => "courses", :action => "export" })
  get("/export_lessons", { :controller => "lessons", :action => "export" })
  get("/export_aq", { :controller => "assessment_questions", :action => "export" })
  get("/export_as", { :controller => "assessment_scores", :action => "export" })

end

app/models/lesson_event.rb
# == Schema Information
#
# Table name: lesson_events
#
#  id         :bigint           not null, primary key
#  seeker_id  :integer
#  lesson_id  :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class LessonEvent < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "lesson_id", "seeker_id", "status", "updated_at"]
  end
  
  enum status: { not_started: 0, teaching_done: 1, practice_done: 2, complete: 3}

  belongs_to :seeker, required: true, class_name: "Seeker", foreign_key: "seeker_id"
  belongs_to :lesson, class_name: "Lesson", foreign_key: "lesson_id"
  


end

app/controllers/lesson_events_controller.rb
class LessonEventsController < ApplicationController
  before_action :require_login


  # PATCH/PUT /lesson_events/1 or /lesson_events/1.json
  def update

    @study_session = LessonEvent.find( params.fetch( :id ) )

    respond_to do |format|

      if @study_session.update(lesson_event_params) == true && @study_session.status == "complete"
        next_lesson = Lesson.find( @study_session.lesson_id + 1)
        format.html { redirect_to course_lesson_path( next_lesson.course, next_lesson), notice: "Well done, friend." }
        format.json { render :show, status: :ok, location: next_lesson }
      elsif @study_session.update(lesson_event_params) == true && @study_session.status != "complete"
        flash[:notice] = "Remember the nearness of the Sacred."
        format.js do
          render template: "lessons/show"
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson_event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def lesson_event_params
    params.require(:lesson_event).permit(:seeker_id, :lesson_id, :status)
  end
end

app/helpers/lesson_events_helper.rb
module LessonEventsHelper
end

app/views/lesson_events/_form.html.erb
<%= form_with(model: @study_session, method: :patch, local: false, remote: true) do |form| %>
  <% if @study_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_session.errors.count, "error") %> Sorry, couldn't save this. Please try refreshing your page. </h2>

      <ul>
        <% @study_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.hidden_field :seeker_id, value: current_seeker.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :lesson_id, value: @study_session.lesson_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :status, value: status_value %>
  </div>

  <div class="form-actions">
    <%= form.submit "Let it Be", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lesson_events/_form_complete.html.erb
<div class="container col-4 offset-4">
<br>
  <div class="row">
  <div class="col d-flex justify-content-center align-items-center">
    <%= form_with(model: study_session, method: :patch, local: false, remote: true) do |form| %>
      <% if study_session.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(study_session.errors.count, "error") %> Sorry, couldn't save this. Please try refreshing your page. </h2>

          <ul>
            <% study_session.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.hidden_field :seeker_id, value: current_seeker.id %>
      </div>

      <div class="field">
        <%= form.hidden_field :lesson_id, value: study_session.lesson_id %>
      </div>

      <div class="field">
        <%= form.hidden_field :status, value: status_value %>
      </div>

      <div class="form-actions">
        <%= form.submit "Complete My Practice", class: "btn-success btn", style: "font-family: EricaOne; font-size: 150%; border-radius: 0.25rem; box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22)" %>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/lesson_events/edit.html.erb
<h1>Editing Lesson Event</h1>

<%= render 'form', lesson_event: @lesson_event %>

<%= link_to 'Show', @lesson_event %> |
<%= link_to 'Back', lesson_events_path %>

app/views/lesson_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lesson Events</h1>

<table>
  <thead>
    <tr>
      <th>Seeker</th>
      <th>Lesson</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lesson_events.each do |lesson_event| %>
      <tr>
        <td><%= lesson_event.seeker_id %></td>
        <td><%= lesson_event.lesson_id %></td>
        <td><%= lesson_event.status %></td>
        <td><%= link_to 'Show', lesson_event %></td>
        <td><%= link_to 'Edit', edit_lesson_event_path(lesson_event) %></td>
        <td><%= link_to 'Destroy', lesson_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson Event', new_lesson_event_path %>

app/views/lesson_events/new.html.erb
<h1>New Lesson Event</h1>

<%= render 'form', lesson_event: @lesson_event %>

<%= link_to 'Back', lesson_events_path %>

app/views/lesson_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seeker:</strong>
  <%= @lesson_event.seeker_id %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @lesson_event.lesson_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lesson_event.status %>
</p>

<%= link_to 'Edit', edit_lesson_event_path(@lesson_event) %> |
<%= link_to 'Back', lesson_events_path %>